### ISSUE TITLE
Required profile field showing error on profile save even if it's there

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#1219]

**Comment by FatihKoz** [comment]
Just an addition to this, as a side note ... When this happened to me, I found that the profile field name had a space in it like `IVAO ID` , when i changed the profile field's name to `IVAO` it was ok.

So it may be related with the naming conversion and somehow it looks for a non existing name thus giving out an error.

**Comment by FatihKoz** [comment]
![image](https://user-images.githubusercontent.com/74361521/197837117-cbb91f53-41cf-44d0-9b7c-a40605a9e702.png)

![image](https://user-images.githubusercontent.com/74361521/197837289-e5ec3157-6be9-4f0e-bc48-5cc6e56a7e14.png)

As my previous posts and PR already states, we do not have any details about the error... So my answer is still same (since Jan 4)

**Comment by YashGovekar** [comment]
> ![image](https://user-images.githubusercontent.com/74361521/197837117-cbb91f53-41cf-44d0-9b7c-a40605a9e702.png)
> 
> ![image](https://user-images.githubusercontent.com/74361521/197837289-e5ec3157-6be9-4f0e-bc48-5cc6e56a7e14.png)
> 
> As my previous posts and PR already states, we do not have any details about the error... So my answer is still same (since Jan 4)

Okay
