### ISSUE TITLE
No .env

### ISSUE THREAD

**Issue by benmaxlevy** [nabeelio/phpvms#1253]
No .env... why are you guys breaking Laravel standards?

**Comment by lunairdev** [comment]
the .env exists it is just called env.php instead of .env

**Comment by nabeelio** [comment]
Yes it's renamed. Since this might be installed on shared hosts, this helps to prevent credential leakage in case someone isn't pointing to the public folder. Might not be as much of a problem now. Dot files are also hidden by default on cpanel, so this more easily exposes the configuration to people instead of the question "where's the .env file" being repeatedly asked

**Comment by FatihKoz** [comment]
> No .env... why are you guys breaking Laravel standards?

Just for fun maybe.
