### ISSUE TITLE
Cache not being cleaned properly (Bug Report)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1563]
When clicked `Clear all caches` button only deletes phpvms v7 cached application files from `bootstrap/cache` folder and does not delete module and theme cache.

**Version**
7.0.0-dev+230630.d76389

**To Reproduce**
1. Go to Admin > Maintenance
2. Click on `Clear all caches` button
3. Check `bootstrap\cache` folder with a file manager for timestamps
4. See the difference and not deleted old files

**Expected behavior**
All cache related files should be deleted

![image](https://github.com/nabeelio/phpvms/assets/74361521/d2c7cb33-b18d-4137-a869-cfb4385f0cf5)

**Comment by FatihKoz** [comment]
@nabeelio , @arthurpar06 any ideas about this ?

I tried checking laravel docs and forums, found nothing useful so far.

**Comment by arthurpar06** [comment]
I remember trying to fix this at one time. I believe that for the theme you have to use the `artisan theme:refresh-cache` command. A  solution to fix only the themes.php would have been to add this command to the controller. For the modules I remember looking but not finding

**Comment by arthurpar06** [comment]
I think it's mainly that the cache files are not managed by Laravel directly but by 3rd parties. My fork of `igaster/laravel-theme` for themes.php and `nwidart/laravel-modules` for modules. They must have separate commands because I think that the Laravel cache commands only empty the cache that Laravel owns (cache of Laravel itself and not the one created by 3rd parties)

**Comment by FatihKoz** [comment]
Mystery is, these two were being deleted back in time (good old days)... When we lost that ability I forgot, probably during laravel 10 switch :(
