### ISSUE TITLE
Accept alternative airport as new destination

### ISSUE THREAD

**Issue by wbox** [nabeelio/phpvms#1572]
**Is your feature request related to a problem? Please describe.**
Whenever is required to land on the alternative airport due to weather or other reasons the system assumes you landed on the original destination airport.

**Describe the solution you'd like**
It would be great if the system places the aircraft and the pilot on the landed airport. I understand the Virtual Airlines would have plan flights departing from the alternative airports but I don't think this would be an issue since most of the time the airlines have regular flights to the these airports anyway.

**Describe alternatives you've considered**
As an alternative, the system could have an "Deviation landing report" page where the pilot would "file a report" explaining why he/she had to land on the alternative airport. This report could be auto approved as well as required a staff to approve. It all depends on how the Virtual Airlines' manager decide to do it. When the report is filed and approved the pilot and the aircraft would be place to the airport where they have landed and not the one filed on the flight plan.

**Additional context**
This would provide even more realism to the Virtual Airlines operations using phpvms.

**Comment by FatihKoz** [comment]
I do agree placing the pilot and aircraft to the diversion airport, however there are some problems with this

* What will happen if the airport in question is not in airline's database 
Considering above, if the airline does not enable automatic airport lookups, pilot and aircraft will be stuck there

* What will happen if the airline does not allow free flights and have no flights between diversion and intended destinations
Pilot will be forced to fly somewhere else instead of their intended destinations, or can get stuck there

* What will happen if a pilot crashes (this is still recorded as a landing, we do not have a crash check) in the middle of nowhere
This will trigger more problems as it will can be a really not suitable airport to fly (combined with above items)

So, placing assets is easy and can be done with a simple code change, we need to think about possible scenarios and/or admin side solutions to fix them etc.

**Comment by nabeelio** [comment]
If there's no flights out, etc, I think maybe a general feature to "jump" to another airport with some cost makes sense. Maybe a setting for jumpseat cost per mile or something. And that can be used if a pilot is stranded or just wants to fly out from another airport. Thoughts?

**Comment by FatihKoz** [comment]
Well, to be honest this will be down to the airline... Some are strict, not allowing people to fly or move freely, some relaxed. So if there are no flights out from diversion airport, then this must be considered for moving or allowing people to jump with options.

As an alternative option, we can define a "move back to departure airport" too... I mean if VA does not want to allow lookups or  and does not want any movement about diversions, then we can move the assets back to the starting point instead of destination or diversion airports.

I am calculating "jump seat travel" prices per distance, so it would make sense but what will be the cost of moving the aircraft ? I am calculating the fuel flow and using distance + other expenses when moving aircraft, so will v7 do that too ?

In the end, moving people is easy :) Side effects (cost, flights, limits) and options are really tricky ;)

**Comment by nabeelio** [comment]
Good points, I was just addressing the pilot moving. Maybe there are jump costs for a subfleet too? It can be enabled/disabled. Not explicitly to the departure airport, but maybe that's an option and also only to hubs? And costs for the aircraft make are just fuel and distance?

**Comment by FatihKoz** [comment]
Aircraft transfer cost `(fuel flow per nautical mile * fuel price) * distance` or make it time based like `(fuel flow per minute * fuel price) * ( distance / average cruise speed )`

Either way, we can't make a fixed per distance price... It should vary between aircraft models, imagine moving a C172 and a B748 would cost the same between JFK and BOS :) It would not look good.
