### ISSUE TITLE
Flight  Import - Not Calculating Distance When Field is Left Empty

### ISSUE THREAD

**Issue by bryan737dfw** [nabeelio/phpvms#1660]
**Describe the bug**
When importing flights, the flight distance is not calculated when the distance field is left blank/empty in the import CSV file.

**Version**
version 7.0.0-beta.5

**To Reproduce**
1. Go to the admin > operations > flights page,
2. Click on Import from CSV.
3. Select file to import (that contains empty distance field).
4. Click Start Import button.
5. Once import is successful, go back to the flights page and select once of the imported flights.
6. The distance will be blank.

**Expected behavior**
After the import, the distance should be calculated for the imported flights.

**Screenshots**
Distance field on the imported flight:
![image](https://github.com/nabeelio/phpvms/assets/74014089/96d4382f-3254-4605-808a-b398a4ebd913)

**Additional context**
Attached file used for import test:
[flights-test-import.csv](https://github.com/nabeelio/phpvms/files/13197075/flights-test-import.csv)

**Comment by FatihKoz** [comment]
Additionally it imports the same flights again instead of updating without properly checking their existence.

![image](https://github.com/nabeelio/phpvms/assets/74361521/c4323853-9273-4b76-838a-b45ab33bdff6)

To test this bug, import a file, then re-import same flight without changing any value inside the csv.

Most probably the "empty/blank" issue is affecting `firstOrNew` logic too @nabeelio

**Comment by FatihKoz** [comment]
```php
        // Check/calculate the distance
        if (blank($row['distance'])) {
            $flight->setAttribute('distance', $this->airportSvc->calculateDistance($row['dpt_airport'], $row['arr_airport']));
        }
```

This will solve the distance issue, needs to be placed before the `try/catch` (technically before the `save()` call)

**But duplicate flight import is still there and it is much more important than the distance**
