### ISSUE TITLE
Discord Notifications 

### ISSUE THREAD

**Issue by sgraypgh** [nabeelio/phpvms#1778]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an Admin checkbox for pirep filed notifications 

**Describe alternatives you've considered**
Only solution is to delete webhook and not get wanted award and rank notifications 

**Additional context**

**Comment by Strider2** [comment]
If you go to settings there is a checkbox for it already, that can stop those pirep filed notifications without having to remove the webhook. Go to settings>notifications and you can see all the settings for it. And if you use dispo basic go to the admin part and uncheck the pirep filed notification there too.

**Comment by sgraypgh** [comment]
It is unchecked, but still sending the pirep filed notification. With it unchecked it is not sensed the phase of flight notifications.

**Comment by avs-code** [comment]
**Is your feature request related to a problem? Please describe.**

In notifications Settings Admin panel, there is a pirep filed faulty option, if you set webhook public url, automatically a discord notification is send when a Pirep is filed.
Can't set others options without this option because there isn't check box to activate/deactivate Pirep filed Discord notifications.

**Describe the solution you'd like**
![imagen](https://github.com/nabeelio/phpvms/assets/16170732/0c6dc86f-5b51-4341-aec5-0a2f53bc34fd)


**Describe alternatives you've considered**

**Additional context**
