### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#244]
- [x] Add `opt_in` column
- [x] Show on profile with "email/marketing opt-out" text
- [x] In emailer, check off is marketing email
- [x] Terms and conditions/privacy policy
- [ ] Permanent delete

**Comment by arv187** [comment]
Can be added a blank field to enter personalized scripts cookies and then block this scripts if user click on NO accept?

**Comment by arv187** [comment]
I know that there a code to encapsule scripts, as hold the load of scripts or header, if cookies are accepted then header/scripts are loaded, if not are accepted scripts never loads. 
If my knowledge in java were not almost null, I would help this and more things, I will try to look for the code to see if it only supposes you do copy and paste or it entails more work.

I am thinking that the VA administrators can place, manually editing the file, those additional scripts next to the default code that you are going to include with phpvms7, and thus they would fulfill the GDPR by loading or blocking the scripts contained in that fragment according to whether the user accepts or does not accept, Would it work?  Thanks!

**Comment by arv187** [comment]
https://cookieconsent.insites.com/documentation/javascript-api/

https://cookieconsent.insites.com/documentation/disabling-cookies/

**Comment by arv187** [comment]
The Opt-in must register. Therefore, you should always be able to demonstrate how you have compiled the option so that its legal validity can be proven.

Double opt-in or confirmed opt-in: includes an additional step to confirm the subscription. Once the form has been completed and the request has been sent, click on the confirmation message sent automatically to the new contact. A method to ensure that the email address entered is valid and that the user is the actual owner.

**Comment by nabeelio** [comment]
I'm a little confused about the ask - there already is the double-opt in - they're required to confirm their email address. Do you just want a generic "opt-in" checkbox that the VA can use when developing features that involve tracking?

There's going to be an opt-in checkbox anyway for the emails and unsubscribe

I'll add in the callback code for the cookies - good catch

**Comment by nabeelio** [comment]
Actually it looks like for the cookies that a notice needs to be set that they're being used. I'm not sure how disabling cookies entirely would work. Is that something you can test? Shutting off cookies, logging in and trying to use the site? You can try it on http://demo.phpvms.net

**Comment by arv187** [comment]
> 
> 
> I'm a little confused about the ask - there already is the double-opt in - they're required to confirm their email address. Do you just want a generic "opt-in" checkbox that the VA can use when developing features that involve tracking?
> 
> There's going to be an opt-in checkbox anyway for the emails and unsubscribe
> 
> I'll add in the callback code for the cookies - good catch

Only the described by discord this afternoon, so yes, a future opt-in is that I want to privacy policy and for emails etc.



> 
> 
> Actually it looks like for the cookies that a notice needs to be set that they're being used. I'm not sure how disabling cookies entirely would work. Is that something you can test? Shutting off cookies, logging in and trying to use the site? You can try it on http://demo.phpvms.net

GDPR require that no cookie is accepted without consent (explicit consent, same that register form), not only a notice (implied), usually a warning is included in the cookie policy or in the same message indicating that some of them are technically necessary for the web to work. login etc.

![cookies1](https://user-images.githubusercontent.com/16170732/45829693-ca33b680-bcfb-11e8-8c94-f6cfa68337ec.JPG)

![cookies2](https://user-images.githubusercontent.com/16170732/45829712-d0299780-bcfb-11e8-8da5-910de58ec3c4.JPG)
.
.
.
.
.
.

![cookies3](https://user-images.githubusercontent.com/16170732/45831671-43350d00-bd00-11e8-8f86-876a2ed1e44d.JPG)
### **full text of the article from the image above: Here is an explanation about the cookie consent :** https://www.cookiebot.com/en/cookie-consent/

It is the general norm, but I am not sure if it always applies to all cookies because sometimes there is a distinction between technical/necessary cookies and others, I think so, because get user personal data to remember preferences, etc (login= ¿user id, email, IP?).

I leave the link here in case someone needs to consult to make their compliance with GDPR in the future or it could be included in the forum although it is somewhat focused on jimdo.
https://jimdo-legal.zendesk.com/hc/en-us/articles/360000189886-GDPR

**Comment by nabeelio** [comment]
The cookie consent is already there

**Comment by nabeelio** [comment]
But yeah maybe we need a more complicated one

**Comment by arv187** [comment]
If you want to keep the consent cookie that you currently have on the demo page, you only have to use option 3. Opt-in (Ask users to opt into cookies (Advanced)) it does not seem difficult for a programmer.
https://cookieconsent.insites.com/documentation/compliance/
