### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by kferrano** [nabeelio/phpvms#31]
How to install this? I found no install.php?

**Comment by phpmods** [comment]
This phpVMS version is currently under development. More information can be found here: https://forum.phpvms.net/topic/24719-just-a-tease

**Comment by nabeelio** [comment]
Hey, there's no installer. I wouldn't suggest installing it just yet because it's changing on the daily, esp with database changes and resets that wipe out all your data. 

However, if you want to try it out, there are some instructions in the README file. You'll need to point your webserver to the `public_html` folder.
