### ISSUE TITLE
Subfleet CSV import

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#476]
Importing CSV does not update the name of aircraft that already exist.

To replicate:
Import CSV for subtype changing the name of a particular subtype that already exists.
It will not change to the new name.

**Comment by nabeelio** [comment]
It's hard to keep track since the index is by name. Does it add a new aircraft?

**Comment by ANA-Haruka** [comment]
Subfleet doesnt have tail number, thats aircraft within subfleet.

I thought the index would be by "Type" since that is whats used for aircraft CSV.

IT doesnt create a new subtype, it just skips.

I think you are confusing the Aircraft import and Subtype import CSV, this is the very first one that contains all subtypes.

**Comment by nabeelio** [comment]
I have an open task, which I naturally can't find right now, to combine the subfleet and aircraft into a single import. I'm probably thinking of that planned transition

**Comment by ANA-Haruka** [comment]
I saw that, was closed #233

**Comment by nabeelio** [comment]
Ah right, I saw my note in that, they're separate because the subfleet does have extra information. What I will do is at least here in this import, if I don't see the subfleet, I'll create it, so it won't error out. But the subfleet import/export will stay as-is because the expenses info and that other stuff.

**Comment by nabeelio** [comment]
Fixed in #503
