### ISSUE TITLE
Get Last Pirep

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#748]
Not sure if I am not calling it properly within profile/index.blade.php, but I am trying to display the pilots last pirep. I went ahead and tried to insert:

```$user->last_priep```

This does not seem to get any information. However my work around for this is:

```
                Latest Flight
                <span class="badge badge-primary badge-pill">
                <a style="color:#fff!important;" href="pireps/
                  {{$user->pireps->where('state','2')->first()->id}}
                ">

                  {{$user->pireps->where('state','2')->first()->airline->icao}}
                  {{$user->pireps->where('state','2')->first()->flight_number}}
                </a>
                </span>
```

**Comment by web541** [comment]
That should work as the last pirep is [grabbed based on](https://github.com/nabeelio/phpvms/blob/dev/app/Models/User.php#L227) the last_pirep_id column of the `users` table. Have you tried this?

```html
Latest Flight
<span class="badge badge-primary badge-pill">
<a style="color:#fff!important;" href="pireps/
	{{ $user->last_pirep->id }}
">

	{{ $user->last_pirep->airline->icao }}
	{{ $user->last_pirep->flight_number }}
</a>
</span>
```

If that doesn't work then potentially the pirep isn't being loaded automatically by Auth. So in the ProfileController you may have to lazy load it:
```php
'user' => Auth::user()->load('last_pirep')
```

I would also change the href attribute to use `route` instead:
```html
href="{{ route('frontend.pireps.show', [
                      $user->last_pirep->id]) }}"
```

**Comment by nickkecooper** [comment]
@web541 Thanks for the input, I did try that piece of code and it was still empty. I will wait for @nabeelio to see if this is a bug.

**Comment by nabeelio** [comment]
`$user->last_pirep` should work, I just tested it in the unit tests with:

```php
$pilot = User::find($user->id);
$last_pirep = $pilot->last_pirep;
$this->assertEquals($pilot->last_pirep_id, $last_pirep->id);
```
How are you using it? Just to get the ID or are the fields also empty? I don't think it does a load unless you try to access a property.

I'm not sure there's a way to eager-load with Auth::user(). Looking through the code, I've been doing (for example, DashboardController):
```php
$last_pirep = $this->pirepRepo->find($user->last_pirep_id);
```

In the unit tests, I do:

```php
$pilot = User::find($user->id);
$last_pirep = Pirep::where('id', $pilot->last_pirep_id)->first();
```

Which btw, the tests are a good spot to look for the different usages. However, what you're doing seems fine, since you're filtering by a state. I would just change this:

```php
$user->pireps->where('state', PirepState::ACCEPTED)->first()->id;
```

**Comment by nickkecooper** [comment]
I am using the ```{{$user->last_pirep}}``` in the profile blade. But it doesn't display any information. If I continue to display it the way I have it, I needed to check for an empty array. Final code I used:

```
                Latest Flight
                <span class="badge badge-primary badge-pill">
                  @if ($user->pireps->isEmpty())
                  None
                  @else
                <a style="color:#fff!important;" href="pireps/
                 {{$user->pireps->where('state','2')->first()->id}}">
                  {{$user->pireps->where('state', PirepState::ACCEPTED)->first()->airline->icao}}
                  {{$user->pireps->where('state','2')->first()->flight_number}}
                </a>
                @endif
                </span>
```

**Comment by nabeelio** [comment]
I would change that to be: 
```
@php
$pirep = $user->pireps->where('state', PirepState::ACCEPTED)->first();
@endphp
{{ $pirep->id}}
{{ $pirep->airline_id }}
```

That way you're not doing multiple queries (I think the tag is `@php`, check the Laravel docs). How are you setting `$user` to the template?

**Comment by web541** [comment]
Yeah @php is the blade tag. I think he's using the [ProfileController](https://github.com/nabeelio/phpvms/blob/dev/app/Http/Controllers/Frontend/ProfileController.php#L74) for the $user.

As for eager loading Auth::user(), I think because it's already fetched you'd be better off lazy loading it but if you use the `$with` property on the User model I would think that it would eager load it (if Auth::user() has a User instance on it). But I see merit in keeping the User small too for when you don't need the last_pirep.

**Comment by nickkecooper** [comment]
@web541 Is correct I am using the ProfileController and this also displays awards which is super helpful! 

@nabeelio Great idea I didn't think to call it just once. I also got creative with display latest flights by using the following:

```
    @foreach ($user->pireps->whereIn('state',['1','2','6'])->take(10) as $pirep)
    <tr>
      <td><a href="pireps/{{$pirep->id}}">{{$pirep->airline->icao}}{{$pirep->flight_number}}</a></td>
      <td>{{$pirep->dpt_airport_id}}</td>
      <td>{{$pirep->arr_airport_id}}</td>
      <td>{{$pirep->aircraft->name}}</td>
      <td>{{$pirep->flight_time}}</td>
      <td>{{ date('m/d/Y', strtotime($pirep->created_at)) }}</td>
      <td>{{ PirepState::label($pirep->state) }}</td>
    </tr>
  @endforeach
```

**Comment by nabeelio** [comment]
@nickkecooper Cool, looks good. I'd just stick to using the constants from `PirepState` instead of individual numbers. I don't think they'd ever change, but it's much clearer when looking at it later what they might be. You can also use `$user->pireps->with(['aircraft'])->whereIn(...)` (I think that's the right syntax) so it will eager-load that relationship, instead of doing it at runtime. You'll end up doing only 10 queries, vs 10 initial and then another 10 (one for each in the loop).

There is awards display code... check the tests, I believe it's in there. Maybe in the profile too. 

@web541 Using `with()` there is good idea b/c of the above query issue. There are a bunch of places in the code where I'm not doing that and I need to fix... I got a bunch in the API but it makes a HUGE difference in load time (I think the user profile load went from 1s under 100ms)

**Comment by nickkecooper** [comment]
@nabeelio Thanks for the tip! I did not know I could use the PirepState within a where statement!

**Comment by nabeelio** [comment]
Awesome!
