### ISSUE TITLE
Pirep Finance Fuel Logic

### ISSUE THREAD

**Issue by CRolfe87** [nabeelio/phpvms#807]
Would be hugely helpful if we could improve slightly on the fuel finance calculation so we can try to manage our fuel costs by doing this kind of calculation on the Pirep Finance:

```
$prevacftpirep = Previous PIREP for $pirep->aircraft_id

if ($pirep->dpt_airport =  $prevacftpirep->arr_airport)
	{if (($prevacftpirep->block_fuel - $prevacftpirep->fuel_used) < $pirep->block_fuel)
		{$fuel_used = $pirep->block_fuel - ($prevacftpirep->block_fuel - $prevacftpirep->fuel_used));}
	else {$fuel_used = 0;};}
else {$fuel_used = $pirep->block_fuel;}
```
I probably messed up the syntax, but I think you get the point.

Example:
AC REG     DEP-ARR    block_fuel   fuel_used
N12345    MIA-DEN    30,000       24,000
N12345    DEN-SFO     18,000       12,000 (pirep being financed)

Math would be: (18,000 - (30,000-24,000)) * $ap->fuel_jeta_cost

This should work for everyone and give a more accurate cost.

**Comment by nabeelio** [comment]
Hi, so you want to basically account for any leftover fuel as being paid for already?

**Comment by CRolfe87** [comment]
Yes, essentially.

**Comment by nabeelio** [comment]
I've added this to the roadmap since I might have to make a few other changes for this

**Comment by FatihKoz** [comment]
Instead of doing the remaining fuel calculations from previous pirep of the ac, I would suggest having it written on the database after each flight and then used for the next flight same aircraft does ... That field on the db could be used in views to show the pilots how much fuel each a/c has on board.

So here is my math/logic for fuel expense ;

*At Flight Start (before Engine Start or Off Block)*

```
if (setting('pireps.advanced_fuel'), true) {
  if ($pirep->aircraft->remaining_fuel) {
    if ($pirep->aircraft->remaining_fuel > $pirep->block_fuel) {
        $finance->fuel_amount = 0 ; // *
    } else { $finance->fuel_amount = $pirep->block_fuel - $pirep->aircraft->remaining_fuel ; } // **
  } else {
    $finance->fuel_amount = $pirep->block_fuel ; } // ***
} else {
    $finance->fuel_amount = $pirep->fuel_used ; // ****
}

```
*At Flight End (after On Block or Engines Off or just when the pilot clicks End Flight button)*

   ` $pirep->aircraft->remaining_fuel->save()`

In textual terms for humans;

If this is the first flight of the aircraft : 
Pay for the block fuel 'cause you uplifted all (like in the real world), technically there were no records of remaining_fuel in the database. ( *** line of if block)

But if the aircraft was used before and had some fuel left in her tanks : 
Check if the pilot in command is adding anything on top of it and if he does, use the added amount for fuel expense calculations. ( ** line of if block)
If he/she is fine with the fuel at the tanks, then do not charge the company for fuel expense. ( * line of if block )

And if the VA does not want any advanced logic, just base calculations on used fuel as we are doing at the moment ( *** line of if block )

**Comment by nabeelio** [comment]
@FatihKoz this can be closed now?

**Comment by FatihKoz** [comment]
I think we can ... We now have the option to use just fuel used for finances or have the remaining fuel in the equation, so both original author's and my ideas are implemented (i suppose).
