### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#871]
For who did what, and when

**Comment by nabeelio** [comment]
http://www.laravel-auditing.com/

**Comment by FatihKoz** [comment]
Even with or without menitoned package, an audit log, visible to admins (relevant staff) is needed before release.

Currently we do not have logs/records of critical actions. Nothing is logged when a flight, pirep or user is deleted, or settings are changed by who.

**Comment by arthurpar06** [comment]
I completely agree with you.
We could also use https://github.com/spatie/laravel-activitylog, which is quite well-known and commonly used for this purpose. Moreover, since it's developed by Spatie, we have no doubts about it being actively maintained in the future...

The package we choose should offer a certain level of flexibility because we don't want to log everything (we don't want to record every entry creation in certain tables, etc.). I think we should also consider a cleanup strategy because we don't want to keep these logs indefinitely (to avoid ending up with a table that accumulates gigabytes and gigabytes).

**Comment by FatihKoz** [comment]
I agree, also we need to clean up our normal logs, define what is ok with info level, what is needed for debug... Like for example, why do we post a complete SimBrief OFP to our laravel log? It is useless, even for debugging it is not necessary and makes the log extremely long.

And yes, maybe we can keep some important stuff (like deleting a user is important and records can be kept up to 180 days, but a pirep being edited by some admin, or a fare edit should be kept like 60 days back, then all can be removed)

We need to have some kind of protection, specially on deletes and important edits. No need to have every update logged, specially when it is done by v7 itself. But human interaction with records is critical 😉
