### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Oxymoron290** [nabeelio/phpvms#910]
I've submitted #909 to make formatting updates to the readme and fix some broken links.

I'm now reaching out to ask for guidance on the contents of the [Requirements](https://github.com/Oxymoron290/phpvms/tree/oxymoron/doc#requirements) section as there is discrepancy between it and the [requirements on the official docs](https://docs.phpvms.net/requirements).

Specifically these two questions:

- What is the minimum version of MySQL officially supported by phpVMS/Laravel?
- Should we add `fileinfo` and `bcmath` to the list of requirements in the readme to match the docs?

Once I have feedback on this issue and my PR, I can make the necessary modifications.

**Comment by nabeelio** [comment]
Whoops, I guess I merged yours too early :) The README should match the docs, since that's out of date. As to the minimum MySQL version, that's a good question. I would like it to be 5.7+, but Laravel does support 5.6+, since it's deprecated in 2021. So I think that is fine.

`fileinfo` should be there, too. I would also add a link to the docs repo - https://github.com/phpvms/docs

**Comment by Oxymoron290** [comment]
No problem! Nothing a second PR can't fix. Probably my fault anyway, should have marked it as a draft. I'll make the changes to the README. The repository for the docs is displayed on the webpage for the docs, so I already have a PR in the making for it too. Just a few minor edits. I'll be reaching out later this week with questions about the project so I can contribute more.
