### ISSUE TITLE
Expenses applies for both airlines in Financial Report.

### ISSUE THREAD

**Issue by macofallico** [nabeelio/phpvms#915]
**Describe the bug**
If you set up expenses for a determinate airline it will apply the expenses in the financial report to all the airlines in the V.A

**Version**
Latest Dev

**To Reproduce**
Set up a monthly expense, once its calculated it will show for both airlines in the financial report.
This occurs in general expenses, and in fleet/flight expenses too.

"Airline A" Fleet/Subfleet expense will apply to "Airline A and B"

**Expected behavior**
Apply expenses corresponding to each airline. 

Cant tell if it is the financial report or the expenses logic per se. 

**Screenshots**
https://imgur.com/a/qzS8Mzc

**Comment by SkygroupVirtual** [comment]
Specific expenses are added everywhere. I just added specific expenses for a few aircrafts (Storing Costs due to pandemic) and they are also added to all airlines. (Every Airline is charged for all aircraft that have that expense) also the specific expense for subfleets are added to all airlines. 

I know this is known, I just wanted to push it a little bit - hopefully thats nothing to tricky to solve.

**Comment by macofallico** [comment]
Sorry, but found out that Aircraft xpenses does not respect Airline, will add to all airlines :(
